### ISSUE TITLE
Custom data preparation

### ISSUE THREAD

**Issue by lerndeep** [tanguymagne/UVDoc#1]
Hello 
Thank you for your great work>
Could you please let me know how can I train my custom dataset ?
I have some samples documents images. so I wants to make training data using sample images.

**Comment by tanguymagne** [comment]
Hello,

If you want to train a model using our method, but with your custom dataset, you need to have all the required annotations for every sample. Then you can use the data structure of the Doc3D dataset or our own UVDoc dataset structure and the corresponding dataloader to train the model.

If your dataset has a different structure, you should write a new dataloader. You can get some idea of how to do it by looking at [this file](https://github.com/tanguymagne/UVDoc/blob/main/data_UVDoc.py) (or [this one](https://github.com/tanguymagne/UVDoc/blob/main/data_doc3D.py)).

I hope my answer helps you! Let me know if you need more help

**Comment by lerndeep** [comment]
i have only raw images so to train your module I want to create dataset in uvdoc format.
is it possible?
Could you please let me know how?

**Comment by tanguymagne** [comment]
If you only have raw images of distorted documents, it is unfortunately not possible to train our model with them.
