### ISSUE TITLE
D435 camera

### ISSUE THREAD

**Issue by runxi607** [tanguymagne/UVDoc#2]
Hello author, can we use Intel Realsense D415 camera instead of D435? Thanks for your help!

**Comment by tanguymagne** [comment]
Hello,
We used an SR305 camera, as we found this one to give less noisy depth. But everything can be done with any RGB-D camera.

I think the code for the capture needs to be adapted a little bit for D415 cameras, in particular [here](https://github.com/tanguymagne/UVDoc-Dataset/blob/main/capture/collection/realsense_capture.py#L41) you need to set the resolution for the depth map.

But other than that the capture should work fine.

I hope this answers your question.

**Comment by runxi607** [comment]
> Hello, We used an SR305 camera, as we found this one to give less noisy depth. But everything can be done with any RGB-D camera.
> 
> I think the code for the capture needs to be adapted a little bit for D415 cameras, in particular [here](https://github.com/tanguymagne/UVDoc-Dataset/blob/main/capture/collection/realsense_capture.py#L41) you need to set the resolution for the depth map.
> 
> But other than that the capture should work fine.
> 
> I hope this answers your question.

Thank you for your reply! Do you know how to remove or smooth the noise of the depth map? Thank you!

**Comment by runxi607** [comment]
> I guess you can try to use a spatial Gaussian filter or some other filter. However, the problem with this method is that you will smooth the depth map and lose some sharp features in the piece of paper.
> 
> Another approach would be to use temporal denoising. Usually, the noise of a stereo-depth camera varies with time. So by taking several images in a row and, for instance, averaging them, you might be able to reduce the noise a bit. Of course, this only works if there is no bias in the noise. I don't know enough about the D415 camera to be sure about that, but that is something you could try.

Thank you very much for your help! The noise in the depth map is mainly at the edges of the document, which can have a lot of burrs. Sometimes there are values missing, sometimes there is an extra piece of value。

**Comment by tanguymagne** [comment]
No problem. Indeed it can be a problem. 
Another solution in the case of missing value might be to use a monocular depth estimation (some deep learning methods are quite good) to fill the void.
I'll close the issue, as it is getting a bit unrelated, but you can reach out to me directly if you have further questions on that topic :slightly_smiling_face:

**Comment by runxi607** [comment]
> No problem. Indeed it can be a problem. Another solution in the case of missing value might be to use a monocular depth estimation (some deep learning methods are quite good) to fill the void. I'll close the issue, as it is getting a bit unrelated, but you can reach out to me directly if you have further questions on that topic 🙂

Thank you very much for your help! Best wishes!
