### ISSUE TITLE
how to map a point in the original drawing to the corrected one?

### ISSUE THREAD

**Issue by fengyanWang** [tanguymagne/UVDoc#3]
Thank you very much for your open source of such a great project. Here I have a question for you. After getting the output of the model, how can I map a point in the original drawing to the corrected one? Looking forward to your reply!

**Comment by tanguymagne** [comment]
**Recap of our method**
Our model outputs a grid of size 31 x 45 (width x height). For each of the points of the grid, the model outputs 2 coordinates (x and y) representing the position of the grid on the warped document image.  The outputted grid is not regular but can be associated with a regular grid on [0,1]x[0,1].

So if the output of our model is `out` with shape `31x45x2`, then `out[0,0]` is a vector of size 2 representing the coordinates in the input (warped) document image of the top left corner of the document. 

The points inside the grid are linearly interpolated from the one predicted by the model. Here is the code that allows you to unwarp an image [https://github.com/tanguymagne/UVDoc/blob/main/utils.py#L37-L51](https://github.com/tanguymagne/UVDoc/blob/main/utils.py#L37-L51).

**Mapping a point in the original drawing to the corrected one**
More practically, to map a point in the original drawing to the corrected one, you need to find in which "square of the outputted grid" your point is and then do a linear interpolation. 

This can be done with [scipy.interpolate.griddata](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html), as long as your point is effectively on the document in the original image. In that case `points` would be the coordinated of the points outputted by our model, `values` would be the coordinates of the points in the regular grid, and `xi` would be the query point, that is the point in the original drawing you want to map to the corrected one.

I hope this helps
