### ISSUE TITLE
Custom data

### ISSUE THREAD

**Issue by phongngrbl** [tanguymagne/UVDoc#4]
Thank you for sharing such an amazing project with the open-source community.
I'd like to ask a question regarding the creation of grid2D and grid3D from the Doc3D dataset. How did you generate them? I'm currently experimenting with training your model using a custom dataset, however, my dataset only has BM labels, and I'm encountering issues with generating grid3D labels. 

Once again, thank you for your attention and time to answer my question.

**Comment by tanguymagne** [comment]
The Doc3D dataset contains an image with world coordinates (the folder name is `wc`), which are 3D coordinates. We sampled this image at the 2D grid coordinates.
Unfortunately, if your custom dataset doesn't contain any 3D information, you cannot obtain the grid3D label for it.
