### ISSUE TITLE
2D and 3D grid data of  Doc3D dataset

### ISSUE THREAD

**Issue by sjjzhuri** [tanguymagne/UVDoc#5]
Thank you for your excellent work. I really appreciate that you have open-sourced your project. I'd like to inquire about how the additional 2D and 3D grid data for the Doc3D dataset was obtained. If possible, I would appreciate it if you could share the code used to derive the 2D and 3D data you proposed from the original Doc3D dataset. Thank you very much.

**Comment by tanguymagne** [comment]
I quickly discussed the process of creating the additional 2D and 3D grid data for the Doc3D dataset in #4.
The idea is to sample the backward mapping, and the world coordinate on a regular grid.
I will clean up the code and add it here soon.

**Comment by tanguymagne** [comment]
Here is the code to create a 2D and 3D grid for a Doc3D sample. The code should be self-explanatory, the only thing to know is that you have to give as input the path to the `uv` and `wc` files of the same sample from the Doc3D dataset. 

```python
import argparse
import os

import cv2
import hdf5storage as h5
import numpy as np
import torch
import torch.nn.functional as F
from scipy.interpolate import griddata, interp1d

os.environ["OPENCV_IO_ENABLE_OPENEXR"] = "1"


NORMALIZE_3D = False


def sample(
    fields, positions, normalize_fields=True, normalize_positions=True, position_normalization=None
):
    """Sample a field at given positions."""
    if normalize_positions:
        if position_normalization is None:
            positions_ = positions / positions.shape[:2]
        else:
            positions_ = positions / position_normalization
        positions_ = (positions_ - 0.5) * 2
    else:
        positions_ = positions.copy()
    positions_ = np.reshape(positions_, (1, *positions_.shape))
    positions_ = torch.from_numpy(positions_).float()

    if normalize_fields:
        fields_ = fields.transpose((2, 0, 1)).astype(np.float32) / 255.0
    else:
        fields_ = fields.transpose((2, 0, 1)).astype(np.float32)
    fields_ = np.expand_dims(fields_, 0)
    fields_ = torch.from_numpy(fields_)

    sampled = F.grid_sample(fields_, positions_, align_corners=True, padding_mode="zeros")
    sampled = sampled[0].numpy().transpose((1, 2, 0))

    return sampled


def create_grid(n_horizontal, n_vertical):
    xs = np.linspace(-1 + 1e-10, 1 - 1e-10, n_vertical)
    ys = np.linspace(-1 + 1e-10, 1 - 1e-10, n_horizontal)
    return np.dstack(np.meshgrid(xs, ys))


def complete_nans(arr, kernel=3):
    """Take an array with nans and fill the value with some interpolation."""
    completed = np.copy(arr)
    rows = []
    cols = []
    while np.isnan(completed).any():
        for i in range(completed.shape[0]):
            line = completed[i, :]
            if np.sum(np.isnan(line)) / len(line) > 0.4:
                # Extrapolate to Nan as there are too many nans
                rows.append(interp1d(np.arange(len(line)), line, fill_value="extrapolate"))
            else:
                # Extrapolate to value as there are enough not nans
                rows.append(
                    interp1d(
                        np.where(~np.isnan(line))[0],
                        line[~np.isnan(line)],
                        fill_value="extrapolate",
                    )
                )
        for j in range(completed.shape[1]):
            line = completed[:, j]
            if np.sum(np.isnan(line)) / len(line) > 0.4:
                # Extrapolate to Nan as there are too many nans
                cols.append(interp1d(np.arange(len(line)), line, fill_value="extrapolate"))
            else:
                # Extrapolate to value as there are enough not nans
                cols.append(
                    interp1d(
                        np.where(~np.isnan(line))[0],
                        line[~np.isnan(line)],
                        fill_value="extrapolate",
                    )
                )

        for i in range(completed.shape[0]):
            for j in range(completed.shape[1]):
                if np.isnan(completed[i, j]):
                    vals = [rows[i](j), cols[j](i)]
                    for k in range(1, kernel + 1):
                        if i - k >= 0:
                            vals.append(rows[i - k](j))
                        if i + k < completed.shape[0]:
                            vals.append(rows[i + k](j))
                        if j - k >= 0:
                            vals.append(cols[j - k](i))
                        if j + k < completed.shape[1]:
                            vals.append(cols[j + k](i))
                    completed[i, j] = np.nanmean(vals)
    return completed


def uv2bm(uv, corner_shift=0):
    """Create the correct backward map from the UV map"""

    uv_copy = np.copy(uv)

    s = 448
    uv_copy *= s

    # Contains coordinate of pixels of corrected image in the warped image
    coord_bm_x = uv_copy[:, :, 2]
    coord_bm_y = uv_copy[:, :, 1]

    # Segmentation of the warped document
    mask = uv_copy[:, :, 0] > 1

    # Contains coordinate of document pixels of corrected image in the warped image
    coord_bm_x = coord_bm_x[mask]
    coord_bm_y = coord_bm_y[mask]

    # Contains coordinate in warp image of pixels that contains document
    coord_uv_y, coord_uv_x = np.where(mask)

    # Create a regular grid
    xs = np.arange(448)
    ys = np.arange(448)
    grid_ys, grid_xs = np.meshgrid(xs, ys)

    # Interpolate on this regular grid
    bm_x = (
        griddata(
            points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
            values=coord_uv_x,
            xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
        )
        .reshape(448, 448)[:, ::-1]
        .T
    )
    bm_y = (
        griddata(
            points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
            values=coord_uv_y,
            xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
        )
        .reshape(448, 448)[:, ::-1]
        .T
    )

    # Complete nans in the interpolation outside domain range with "linear interpolation"
    bm_x = complete_nans(bm_x)
    bm_y = complete_nans(bm_y)

    bm_corrected = np.dstack([bm_x, bm_y])

    return bm_corrected


def unwarp_coord3d(uv, coord_3d, corner_shift: float = 0):
    """Create the 3D coordinates from the UV map and the 3D coordinates."""
    uv_copy = np.copy(uv)

    s = 448
    uv_copy *= s

    # Contains coordinate of pixels in corrected image in the warped image
    coord_bm_x = uv_copy[:, :, 2]
    coord_bm_y = uv_copy[:, :, 1]

    # Segmentation of the warped document
    mask = uv_copy[:, :, 0] > 1

    # Contains coordinate of document pixels of corrected image in the warped image
    coord_bm_x = coord_bm_x[mask]
    coord_bm_y = coord_bm_y[mask]

    # Contains 3D coordinate in warp image of pixels that contains document
    coord_3d_x = coord_3d[mask][:, 0]
    coord_3d_y = coord_3d[mask][:, 1]
    coord_3d_z = coord_3d[mask][:, 2]

    # Create a regular grid
    xs = np.arange(448)
    ys = np.arange(448)
    grid_ys, grid_xs = np.meshgrid(xs, ys)

    # Interpolate on this regular grid
    coord_3d_x_grid = (
        griddata(
            points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
            values=coord_3d_x,
            xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
        )
        .reshape(448, 448)[:, ::-1]
        .T
    )

    coord_3d_y_grid = (
        griddata(
            points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
            values=coord_3d_y,
            xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
        )
        .reshape(448, 448)[:, ::-1]
        .T
    )

    coord_3d_z_grid = (
        griddata(
            points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
            values=coord_3d_z,
            xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
        )
        .reshape(448, 448)[:, ::-1]
        .T
    )

    # Complete nans in the interpolation outside domain range with "linear interpolation"
    coord_3d_x_grid = complete_nans(coord_3d_x_grid)
    coord_3d_y_grid = complete_nans(coord_3d_y_grid)[:, ::-1]
    coord_3d_z_grid = complete_nans(coord_3d_z_grid)

    grid_3d = np.dstack([coord_3d_x_grid, coord_3d_y_grid, coord_3d_z_grid])

    return grid_3d


def create_3D_grid(uv, wc, grid):
    """Create the sampled 3D grid from the UV map, the 3D coordinates, and the grid coordinates."""
    im_coord_3d = unwarp_coord3d(uv, wc)

    grid_3d = sample(
        im_coord_3d,
        grid,
        normalize_fields=False,
        normalize_positions=False,
        position_normalization=wc.shape[0],
    )
    return grid_3d


def main(fname, args):
    """Create the 2D and 3D grid from the UV map, the 3D coordinates, and the grid coordinates."""

    wc_ = cv2.imread(args.wc_path, cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
    wc = wc_.astype(float)

    if NORMALIZE_3D:  # Currently set to false
        # scale wc but leave background as (0,0,0)
        msk = ((wc[:, :, 0] != 0) & (wc[:, :, 1] != 0) & (wc[:, :, 2] != 0)).astype(np.uint8) * 255
        xmx, xmn, ymx, ymn, zmx, zmn = (
            1.2539363,
            -1.2442188,
            1.2396319,
            -1.2289206,
            0.6436657,
            -0.67492497,
        )  # calculate from all the wcs
        wc[:, :, 0] = (wc[:, :, 0] - zmn) / (zmx - zmn)
        wc[:, :, 1] = (wc[:, :, 1] - ymn) / (ymx - ymn)
        wc[:, :, 2] = (wc[:, :, 2] - xmn) / (xmx - xmn)
        wc = cv2.bitwise_and(wc, wc, mask=msk)
        wc = np.array(wc, dtype=np.float)
        wc = torch.from_numpy(wc).float()

    # Get UV Map
    uv = cv2.imread(args.uv_path, cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)

    # Create the correct backward map
    # Note : we don't use the provided backward map as we found some innacuracies in it
    bm_corrected = uv2bm(uv)

    # Create a grid and warp it to fit the warped image
    GRID_SIZE = args.grid_res
    grid = create_grid(*GRID_SIZE)
    warped_2Dgrid = sample(bm_corrected, grid, normalize_fields=False, normalize_positions=False)
    warped_3Dgrid = create_3D_grid(uv, wc, grid)

    # Save 2D and 3D grid
    output_file_grid2D = os.path.join(args.grid2D_path, fname[:-3] + "mat")
    output_file_grid3D = os.path.join(args.grid3D_path, fname[:-3] + "mat")
    h5.savemat(output_file_grid2D, mdict={"grid2D": warped_2Dgrid}, format="7.3")
    h5.savemat(output_file_grid3D, mdict={"grid3D": warped_3Dgrid}, format="7.3")

    return True  # , res


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Params")

    parser.add_argument(
        "--uv_path",
        type=str,
        help="Path of the GT UV coordinates",
    )
    parser.add_argument(
        "--wc_path",
        type=str,
        help="Path of the GT 3D coordinates",
    )
    parser.add_argument(
        "--grid2D_path",
        type=str,
        default="./data/grid2D/",
        help="Path to store the GT 2D Grid coordinates",
    )
    parser.add_argument(
        "--grid3D_path",
        type=str,
        default="./data/grid3D/",
        help="Path to store the GT 3D Grid coordinates",
    )
    parser.add_argument(
        "--grid_res",
        nargs="+",
        type=int,
        default=[45, 31],
        help="Resolution of the grid to overlay",
    )

    args = parser.parse_args()
    if len(args.grid_res) == 2:
        args.grid_res = tuple(args.grid_res)
    elif len(args.grid_res) == 1:
        args.grid_res = (args.grid_res, args.grid_res)
    else:
        print("Error: provided grid_res was neither an int or 2-tuple")

    fname = args.uv_path.split("/")[-1].split(".")[0]

    main(fname, args)

```

**Comment by sjjzhuri** [comment]
> Here is the code to create a 2D and 3D grid for a Doc3D sample. The code should be self-explanatory, the only thing to know is that you have to give as input the path to the `uv` and `wc` files of the same sample from the Doc3D dataset.
> 
> ```python
> import argparse
> import os
> 
> import cv2
> import hdf5storage as h5
> import numpy as np
> import torch
> import torch.nn.functional as F
> from scipy.interpolate import griddata, interp1d
> 
> os.environ["OPENCV_IO_ENABLE_OPENEXR"] = "1"
> 
> 
> NORMALIZE_3D = False
> 
> 
> def sample(
>     fields, positions, normalize_fields=True, normalize_positions=True, position_normalization=None
> ):
>     """Sample a field at given positions."""
>     if normalize_positions:
>         if position_normalization is None:
>             positions_ = positions / positions.shape[:2]
>         else:
>             positions_ = positions / position_normalization
>         positions_ = (positions_ - 0.5) * 2
>     else:
>         positions_ = positions.copy()
>     positions_ = np.reshape(positions_, (1, *positions_.shape))
>     positions_ = torch.from_numpy(positions_).float()
> 
>     if normalize_fields:
>         fields_ = fields.transpose((2, 0, 1)).astype(np.float32) / 255.0
>     else:
>         fields_ = fields.transpose((2, 0, 1)).astype(np.float32)
>     fields_ = np.expand_dims(fields_, 0)
>     fields_ = torch.from_numpy(fields_)
> 
>     sampled = F.grid_sample(fields_, positions_, align_corners=True, padding_mode="zeros")
>     sampled = sampled[0].numpy().transpose((1, 2, 0))
> 
>     return sampled
> 
> 
> def create_grid(n_horizontal, n_vertical):
>     xs = np.linspace(-1 + 1e-10, 1 - 1e-10, n_vertical)
>     ys = np.linspace(-1 + 1e-10, 1 - 1e-10, n_horizontal)
>     return np.dstack(np.meshgrid(xs, ys))
> 
> 
> def complete_nans(arr, kernel=3):
>     """Take an array with nans and fill the value with some interpolation."""
>     completed = np.copy(arr)
>     rows = []
>     cols = []
>     while np.isnan(completed).any():
>         for i in range(completed.shape[0]):
>             line = completed[i, :]
>             if np.sum(np.isnan(line)) / len(line) > 0.4:
>                 # Extrapolate to Nan as there are too many nans
>                 rows.append(interp1d(np.arange(len(line)), line, fill_value="extrapolate"))
>             else:
>                 # Extrapolate to value as there are enough not nans
>                 rows.append(
>                     interp1d(
>                         np.where(~np.isnan(line))[0],
>                         line[~np.isnan(line)],
>                         fill_value="extrapolate",
>                     )
>                 )
>         for j in range(completed.shape[1]):
>             line = completed[:, j]
>             if np.sum(np.isnan(line)) / len(line) > 0.4:
>                 # Extrapolate to Nan as there are too many nans
>                 cols.append(interp1d(np.arange(len(line)), line, fill_value="extrapolate"))
>             else:
>                 # Extrapolate to value as there are enough not nans
>                 cols.append(
>                     interp1d(
>                         np.where(~np.isnan(line))[0],
>                         line[~np.isnan(line)],
>                         fill_value="extrapolate",
>                     )
>                 )
> 
>         for i in range(completed.shape[0]):
>             for j in range(completed.shape[1]):
>                 if np.isnan(completed[i, j]):
>                     vals = [rows[i](j), cols[j](i)]
>                     for k in range(1, kernel + 1):
>                         if i - k >= 0:
>                             vals.append(rows[i - k](j))
>                         if i + k < completed.shape[0]:
>                             vals.append(rows[i + k](j))
>                         if j - k >= 0:
>                             vals.append(cols[j - k](i))
>                         if j + k < completed.shape[1]:
>                             vals.append(cols[j + k](i))
>                     completed[i, j] = np.nanmean(vals)
>     return completed
> 
> 
> def uv2bm(uv, corner_shift=0):
>     """Create the correct backward map from the UV map"""
> 
>     uv_copy = np.copy(uv)
> 
>     s = 448
>     uv_copy *= s
> 
>     # Contains coordinate of pixels of corrected image in the warped image
>     coord_bm_x = uv_copy[:, :, 2]
>     coord_bm_y = uv_copy[:, :, 1]
> 
>     # Segmentation of the warped document
>     mask = uv_copy[:, :, 0] > 1
> 
>     # Contains coordinate of document pixels of corrected image in the warped image
>     coord_bm_x = coord_bm_x[mask]
>     coord_bm_y = coord_bm_y[mask]
> 
>     # Contains coordinate in warp image of pixels that contains document
>     coord_uv_y, coord_uv_x = np.where(mask)
> 
>     # Create a regular grid
>     xs = np.arange(448)
>     ys = np.arange(448)
>     grid_ys, grid_xs = np.meshgrid(xs, ys)
> 
>     # Interpolate on this regular grid
>     bm_x = (
>         griddata(
>             points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
>             values=coord_uv_x,
>             xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
>         )
>         .reshape(448, 448)[:, ::-1]
>         .T
>     )
>     bm_y = (
>         griddata(
>             points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
>             values=coord_uv_y,
>             xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
>         )
>         .reshape(448, 448)[:, ::-1]
>         .T
>     )
> 
>     # Complete nans in the interpolation outside domain range with "linear interpolation"
>     bm_x = complete_nans(bm_x)
>     bm_y = complete_nans(bm_y)
> 
>     bm_corrected = np.dstack([bm_x, bm_y])
> 
>     return bm_corrected
> 
> 
> def unwarp_coord3d(uv, coord_3d, corner_shift: float = 0):
>     """Create the 3D coordinates from the UV map and the 3D coordinates."""
>     uv_copy = np.copy(uv)
> 
>     s = 448
>     uv_copy *= s
> 
>     # Contains coordinate of pixels in corrected image in the warped image
>     coord_bm_x = uv_copy[:, :, 2]
>     coord_bm_y = uv_copy[:, :, 1]
> 
>     # Segmentation of the warped document
>     mask = uv_copy[:, :, 0] > 1
> 
>     # Contains coordinate of document pixels of corrected image in the warped image
>     coord_bm_x = coord_bm_x[mask]
>     coord_bm_y = coord_bm_y[mask]
> 
>     # Contains 3D coordinate in warp image of pixels that contains document
>     coord_3d_x = coord_3d[mask][:, 0]
>     coord_3d_y = coord_3d[mask][:, 1]
>     coord_3d_z = coord_3d[mask][:, 2]
> 
>     # Create a regular grid
>     xs = np.arange(448)
>     ys = np.arange(448)
>     grid_ys, grid_xs = np.meshgrid(xs, ys)
> 
>     # Interpolate on this regular grid
>     coord_3d_x_grid = (
>         griddata(
>             points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
>             values=coord_3d_x,
>             xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
>         )
>         .reshape(448, 448)[:, ::-1]
>         .T
>     )
> 
>     coord_3d_y_grid = (
>         griddata(
>             points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
>             values=coord_3d_y,
>             xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
>         )
>         .reshape(448, 448)[:, ::-1]
>         .T
>     )
> 
>     coord_3d_z_grid = (
>         griddata(
>             points=np.vstack([coord_bm_x, coord_bm_y]).T + corner_shift,
>             values=coord_3d_z,
>             xi=np.vstack([grid_xs.flatten(), grid_ys.flatten()]).T,
>         )
>         .reshape(448, 448)[:, ::-1]
>         .T
>     )
> 
>     # Complete nans in the interpolation outside domain range with "linear interpolation"
>     coord_3d_x_grid = complete_nans(coord_3d_x_grid)
>     coord_3d_y_grid = complete_nans(coord_3d_y_grid)[:, ::-1]
>     coord_3d_z_grid = complete_nans(coord_3d_z_grid)
> 
>     grid_3d = np.dstack([coord_3d_x_grid, coord_3d_y_grid, coord_3d_z_grid])
> 
>     return grid_3d
> 
> 
> def create_3D_grid(uv, wc, grid):
>     """Create the sampled 3D grid from the UV map, the 3D coordinates, and the grid coordinates."""
>     im_coord_3d = unwarp_coord3d(uv, wc)
> 
>     grid_3d = sample(
>         im_coord_3d,
>         grid,
>         normalize_fields=False,
>         normalize_positions=False,
>         position_normalization=wc.shape[0],
>     )
>     return grid_3d
> 
> 
> def main(fname, args):
>     """Create the 2D and 3D grid from the UV map, the 3D coordinates, and the grid coordinates."""
> 
>     wc_ = cv2.imread(args.wc_path, cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
>     wc = wc_.astype(float)
> 
>     if NORMALIZE_3D:  # Currently set to false
>         # scale wc but leave background as (0,0,0)
>         msk = ((wc[:, :, 0] != 0) & (wc[:, :, 1] != 0) & (wc[:, :, 2] != 0)).astype(np.uint8) * 255
>         xmx, xmn, ymx, ymn, zmx, zmn = (
>             1.2539363,
>             -1.2442188,
>             1.2396319,
>             -1.2289206,
>             0.6436657,
>             -0.67492497,
>         )  # calculate from all the wcs
>         wc[:, :, 0] = (wc[:, :, 0] - zmn) / (zmx - zmn)
>         wc[:, :, 1] = (wc[:, :, 1] - ymn) / (ymx - ymn)
>         wc[:, :, 2] = (wc[:, :, 2] - xmn) / (xmx - xmn)
>         wc = cv2.bitwise_and(wc, wc, mask=msk)
>         wc = np.array(wc, dtype=np.float)
>         wc = torch.from_numpy(wc).float()
> 
>     # Get UV Map
>     uv = cv2.imread(args.uv_path, cv2.IMREAD_ANYCOLOR | cv2.IMREAD_ANYDEPTH)
> 
>     # Create the correct backward map
>     # Note : we don't use the provided backward map as we found some innacuracies in it
>     bm_corrected = uv2bm(uv)
> 
>     # Create a grid and warp it to fit the warped image
>     GRID_SIZE = args.grid_res
>     grid = create_grid(*GRID_SIZE)
>     warped_2Dgrid = sample(bm_corrected, grid, normalize_fields=False, normalize_positions=False)
>     warped_3Dgrid = create_3D_grid(uv, wc, grid)
> 
>     # Save 2D and 3D grid
>     output_file_grid2D = os.path.join(args.grid2D_path, fname[:-3] + "mat")
>     output_file_grid3D = os.path.join(args.grid3D_path, fname[:-3] + "mat")
>     h5.savemat(output_file_grid2D, mdict={"grid2D": warped_2Dgrid}, format="7.3")
>     h5.savemat(output_file_grid3D, mdict={"grid3D": warped_3Dgrid}, format="7.3")
> 
>     return True  # , res
> 
> 
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser(description="Params")
> 
>     parser.add_argument(
>         "--uv_path",
>         type=str,
>         help="Path of the GT UV coordinates",
>     )
>     parser.add_argument(
>         "--wc_path",
>         type=str,
>         help="Path of the GT 3D coordinates",
>     )
>     parser.add_argument(
>         "--grid2D_path",
>         type=str,
>         default="./data/grid2D/",
>         help="Path to store the GT 2D Grid coordinates",
>     )
>     parser.add_argument(
>         "--grid3D_path",
>         type=str,
>         default="./data/grid3D/",
>         help="Path to store the GT 3D Grid coordinates",
>     )
>     parser.add_argument(
>         "--grid_res",
>         nargs="+",
>         type=int,
>         default=[45, 31],
>         help="Resolution of the grid to overlay",
>     )
> 
>     args = parser.parse_args()
>     if len(args.grid_res) == 2:
>         args.grid_res = tuple(args.grid_res)
>     elif len(args.grid_res) == 1:
>         args.grid_res = (args.grid_res, args.grid_res)
>     else:
>         print("Error: provided grid_res was neither an int or 2-tuple")
> 
>     fname = args.uv_path.split("/")[-1].split(".")[0]
> 
>     main(fname, args)
> ```

Thank you very much for providing this code, much appreciated.

**Comment by shallweiwei** [comment]
@tanguymagne May I ask if I want to get the bm of the uvdoc dataset, can I also use the above code and just change the size?

**Comment by tanguymagne** [comment]
@shallweiwei The 2D grid of the UVDoc dataset is actually a low-resolution backward mapping.
To get a high-resolution backward mapping, you can simply upsample it.

This is what we are doing when unwarping an image. The code to do this is [here],(https://github.com/tanguymagne/UVDoc/blob/main/utils.py#L46-L48), where `point_positions` is the 2D grid and `img_size` indicate the size of the backward mapping you want.
I hope this helps

**Comment by shallweiwei** [comment]
Thank you for your answer.
