### ISSUE TITLE
Train test split

### ISSUE THREAD

**Issue by AKA-123** [tanguymagne/UVDoc#6]
Thank you for your work!
I received the following error. "FileNotFoundError: [Errno 2] No such file or directory: './data/doc3D/traindoc.txt' when trying to replicate the training of your model. In the dataloader there are separate files for specifying the training and validation data for Doc3D. Can you please specify the split you used? Or could you please share the .txt file format?

**Comment by tanguymagne** [comment]
Hi,
The `.txt` files specifying the split we used are available alongside the Doc3D grid here [Doc3D_grid.zip](https://igl.ethz.ch/projects/uvdoc/Doc3D_grid.zip).
