### ISSUE TITLE
你们模型是不是只适合用在扭曲文本图片上？我想用在不扭曲的倾斜文本上能不能有好的效果？

### ISSUE THREAD

**Issue by LMR2018** [tanguymagne/UVDoc#7]
你们模型是不是只适合用在扭曲文本图片上？我想用在不扭曲的倾斜文本上能不能有好的效果？如果想用在不扭曲的倾斜文本上，我应该怎么准备数据和模型的训练？

**Comment by tanguymagne** [comment]
Hi,

I hope I understood your question correctly. It is possible to use our model on simply skewed document images, it should still work, and you can use our model as for any other input (see [here](https://github.com/tanguymagne/UVDoc/tree/main?tab=readme-ov-file#demo)).

However, for such simple cases, other methods might work better as they take into account the additional information that the paper is only skewed. For instance, methods that detect the corners of the document and apply the correct perspective transform might be better suited for your case.
