### ISSUE TITLE
How to get key point of image?

### ISSUE THREAD

**Issue by HERIUN** [tanguymagne/UVDoc#9]
I want document corner point coordinates. Is it possible?

**Comment by tanguymagne** [comment]
Hi,
It is possible to obtain the coordinates of the document corner predicted by our network. You simply need to select the 4 corners of the output 2D grid.

To that end, in [this script](https://github.com/tanguymagne/UVDoc/blob/main/demo.py#L29C5-L29C22) you can take the coordinates at position [0,0], [0, -1], [-1, 0] and [-1, -1] of `point_positions2D`.
